In [1]:
import numpy as np
#Define the key matrix
key_matrix = np.array(
    [
        [9, 7, 11, 13],
        [4, 7, 5, 6],
        [2, 21, 14, 9],
        [3, 23, 21, 8]
    ]
)
#Finding inverse of the key matrix
det = int(np.round(np.linalg.det(key_matrix)))
det_inv = pow(det, -1, 26)
inv_key_matrix = det_inv * (np.round(det*np.linalg.inv(key_matrix)).astype(int)) %26

In [2]:
#Input section
plaintext = input("Enter the plaintext: ")
text = plaintext.replace(" ","")
text_len = len(text)
key_len = len(key_matrix)
text = text.upper()

#Add extra character if required
if (text_len % key_len) !=0:
    extra = key_len - (text_len % key_len)
    for i in range (extra):
        text = text + "X"
print(text)

#Create plaintext array
text_len = len(text)
text_array = np.zeros(text_len, dtype=int)

i = 0
for char in text:
    value = ord(char) - 65
    text_array[i] = value
    i = i + 1
    
column = len(key_matrix)
row =  len(text_array)//column
#Reshaping the array
text_array = text_array.reshape(row, column)
print("Plaintext array of numerical values: \n",text_array)


Enter the plaintext:  Shehad Uj Jahan


SHEHADUJJAHANXXX
Plaintext array of numerical values: 
 [[18  7  4  7]
 [ 0  3 20  9]
 [ 9  0  7  0]
 [13 23 23 23]]


In [3]:
#Encryption Section
cipher_array = np.dot(text_array, key_matrix)%26
ciphertext = ""
for i in range(row):
    for j in range(column):
        char = chr(cipher_array[i][j]+97)
        ciphertext = ciphertext + char
print("Ciphertext: ",ciphertext)

#Decryption Section
decrypted_array = np.dot(cipher_array, inv_key_matrix)%26
decrypted_text = ""
for i in range(row):
    for j in range(column):
        char = chr(decrypted_array[i][j]+97)
        decrypted_text = decrypted_text + char
print("Decrypted plaintext: ",decrypted_text)

Ciphertext:  leuebyqkrcpymqxw
Decrypted plaintext:  shehadujjahanxxx
